import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import ReadyToCook from '@/components/ReadyToCook';
import type { Metadata } from 'next';
import { Nunito, Nunito_Sans } from 'next/font/google';
import './globals.css';

const nunito = Nunito({
  display: 'swap',
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${nunito.className} ${nunitoSans.variable} antialiased bg-green-100`}>
        <Header />
        <main>
          {children}
          <ReadyToCook />
        </main>
        <Footer />
      </body>
    </html>
  );
}
